[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci",
  "cd frontend && npm ci && cd ..",
]

[phases.build]
cmds = [
  "cd frontend && npm run build && cd ..",
  "cp -r frontend/dist public",
  "npx prisma generate",
  "npm run build",
]

[start]
cmd = "npx prisma migrate deploy && node dist/app.js"
